### ISSUE TITLE
Why does the website not display any download links?

### ISSUE THREAD

**Issue by wchisme2000** [uup-dump-dev/website-public#7]
The website doesn't look normal either...

**Comment by abbodi1406** [comment]
Why don't you be more clear?

**Comment by wchisme2000** [comment]
> Why don't you be more clear?
Sorry, no matter what system category I choose, it is the same. No download link will be displayed

![image](https://user-images.githubusercontent.com/58378837/211960435-f1aa453f-004d-4f13-998e-18397eb8013b.png)

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/215297059-4b482470-16a2-4889-9da7-537f2d505d07.png)

oh dude. you need the iso first.

example i select lastest preview build
![image](https://user-images.githubusercontent.com/91467886/215297095-289ea714-cb2d-4902-876e-8a018da5e362.png)

select one of them
![image](https://user-images.githubusercontent.com/91467886/215297103-a1b5b4ac-e937-4daa-8c22-dd88bde6e148.png)

just follow the instructions
![image](https://user-images.githubusercontent.com/91467886/215297114-1798b7ce-5961-4fe7-8aaf-d209bdbbf4c9.png)

when you done. click download package. extract and compile your own iso
![image](https://user-images.githubusercontent.com/91467886/215297156-344ea54e-3cb4-4362-b680-9e4d6bc4769b.png)

**Comment by wchisme2000** [comment]
Thank you very much. Finally, I found that the Chinese page link of the website has changed. The original favorite link suffix is/zh-cn, but now the link has changed to/? Lang=zh-cn, so an error occurred
